// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetHelloWorld() {
  return window['go']['main']['App']['GetHelloWorld']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function WindowCenter() {
  return window['go']['main']['App']['WindowCenter']();
}

export function WindowFullscreen() {
  return window['go']['main']['App']['WindowFullscreen']();
}

export function WindowHide() {
  return window['go']['main']['App']['WindowHide']();
}

export function WindowIsFullscreen() {
  return window['go']['main']['App']['WindowIsFullscreen']();
}

export function WindowIsMaximised() {
  return window['go']['main']['App']['WindowIsMaximised']();
}

export function WindowIsMinimised() {
  return window['go']['main']['App']['WindowIsMinimised']();
}

export function WindowMaximize() {
  return window['go']['main']['App']['WindowMaximize']();
}

export function WindowMinimize() {
  return window['go']['main']['App']['WindowMinimize']();
}

export function WindowResize(arg1, arg2) {
  return window['go']['main']['App']['WindowResize'](arg1, arg2);
}

export function WindowSetTitle(arg1) {
  return window['go']['main']['App']['WindowSetTitle'](arg1);
}

export function WindowShow() {
  return window['go']['main']['App']['WindowShow']();
}

export function WindowUnmaximize() {
  return window['go']['main']['App']['WindowUnmaximize']();
}
