// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppVersion():Promise<string>;

export function GetHelloWorld():Promise<string>;

export function GetPlatform():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function WindowCenter():Promise<void>;

export function WindowFullscreen():Promise<void>;

export function WindowHide():Promise<void>;

export function WindowIsFullscreen():Promise<boolean>;

export function WindowIsMaximised():Promise<boolean>;

export function WindowIsMinimised():Promise<boolean>;

export function WindowMaximize():Promise<void>;

export function WindowMinimize():Promise<void>;

export function WindowResize(arg1:number,arg2:number):Promise<void>;

export function WindowSetTitle(arg1:string):Promise<void>;

export function WindowShow():Promise<void>;

export function WindowUnmaximize():Promise<void>;
